# GitHub Pages configuration for skinbyhaxton.com
title: "Skin by Haxton"
description: "Archived website from skinbyhaxton.com"
baseurl: "/skinbyhaxton"
url: "https://yourusername.github.io"

# GitHub Pages settings
markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
